In [1]:
# often, numpy is shortened to np
import numpy as np

In [31]:
arr1 = np.linspace(0, 5, 20)
print(arr1)
arr1 = np.arange(0, 40, 2)
print(arr1)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [32]:
arr2 = arr1.reshape(4, 5)
arr2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [33]:
arr3 = np.sin(arr1)
arr3

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162,  0.55142668,  0.52908269, -0.99177885,  0.29636858])

In [34]:
# easily find the size of an array
print('arr name:', 'arr1', 'arr2')
# ndim will print the number of dimensions
print('arr ndim:', arr1.ndim, arr2.ndim)
# you can know the size of the array (how many entries)
print('arr size:', arr1.size, arr2.size)
# and the shape (the dimensions / lengths along those dimensions)
print('arr shape:', arr1.shape, arr2.shape)

arr name: arr1 arr2
arr ndim: 1 2
arr size: 20 20
arr shape: (20,) (4, 5)


In [35]:
# sort an array
arr3.sort()
arr3

array([-0.99177885, -0.98803162, -0.90557836, -0.7568025 , -0.75098725,
       -0.54402111, -0.53657292, -0.28790332, -0.2794155 , -0.00885131,
        0.        ,  0.27090579,  0.29636858,  0.52908269,  0.55142668,
        0.76255845,  0.90929743,  0.91294525,  0.98935825,  0.99060736])

In [36]:
# fill an array with ones or zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])