In [1]:
import numpy as np # alias is "np"

In [8]:
# arr1 = np.linspace(0, 5, 10)
# print(arr1) # Ctrl + / creates an automatic comment
# to run a cell, type Shift + Enter
arr1 = np.arange(0, 40, 2)
print(arr1)

# arange is good for periodic data. ex:
# for i in np.arange(0, len(timeseries), 24):
#     one_day = timeseries[i:i+24]

#  what's really happening with arange
# i = 0
# while (i < 40):
#     print(i)
#     i+=2

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [10]:
arr2 = arr1.reshape(4, 5)
arr2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [18]:
arr3 = np.sin(arr1)
arr3

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162,  0.55142668,  0.52908269, -0.99177885,  0.29636858])

In [17]:
print('dimension',arr1.ndim, arr2.ndim, arr3.ndim)
print('size',arr1.size, arr2.size, arr3.size)
print('shape',arr1.shape, arr2.shape, arr3.shape)

dimension 1 2 2
size 20 20 20
shape (20,) (4, 5) (4, 5)


In [22]:
arr3.sort()
arr3

array([-0.99177885, -0.98803162, -0.90557836, -0.7568025 , -0.75098725,
       -0.54402111, -0.53657292, -0.28790332, -0.2794155 , -0.00885131,
        0.        ,  0.27090579,  0.29636858,  0.52908269,  0.55142668,
        0.76255845,  0.90929743,  0.91294525,  0.98935825,  0.99060736])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])